branches:
  except:
    - gh-pages
image: Visual Studio 2017
init:
- tzutil /s "Central Standard Time"
- cmd: node -v
- cmd: npm -v
- cmd: python -V
- cmd: pip -V
- ps: $PSVersionTable
install:
  - ps: Install-Product node 8
  - appveyor-retry chocolatey install make
  - appveyor-retry chocolatey install gnuwin32-coreutils.portable
  - appveyor-retry npm install
  - pip install tox
  - ps: Start-Process npm "run httpbin" -PassThru
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk && git checkout 2da530aa5e6d6bcaf994ed1b2613a98872a428c8 && cd ..
  - ps: emsdk\emsdk install sdk-1.37.36-64bit
  - ps: emsdk\emsdk activate sdk-1.37.36-64bit
platform:
  - Win32
configuration:
  - Debug
before_build:
# TODO capture standard out and error to log at the end?
# TODO script needed to wait for server startup?
  - make lint
  - npm run lint
build:
  project: Vireo_VS/VireoCommandLine.sln
after_build:
  - cmd /c make-it\appveyor-support\setup-env-and-make-vjs.bat
  - nuget pack VireoSDK.nuspec
test_script:
  - make testjs
  - make testnative
  - make testhttpbin
  - npm run test -- --browsers FirefoxHeadless
  - npm run test -- --browsers IE --skip-tags FailsIE

artifacts:
  - path: '*.nupkg'
deploy:
  provider: NuGet
  artifact: '/.*\.nupkg/'
  api_key:
    secure: CTuSIf5+uQFtl563xNMg4BC5WnAnYV1MfeVavlVgsP4P+zJVsrdWSjydgMEJYQb5